keys:
  - users:
      - &walther age1hqdgs3f0vz4vmzcplu87zkypltk663sdu4660h4czrx5739y4p7sv97nwg
      - &sveske age1xx02tc8pj9v6hd3vctw5pnm7840alzdz8t88qaefd4e7gddl9yhsdplsp7
      - &redux age1n025gq6t6sp3uwwmdge8kytzs520hxmmr7l3e7hh9ezzwnm3aqaqhewle2
  - hosts:
      - &SussyBox age103p4534fyaqcdgp0tuvydp4ex92thlry483yvgauvf5denzs7gssugurue
      - &waltherbox age1u3cls43238kr2v0gkgjfezzrcr3lqa2sfkkzw46ey6md6gnln30quhelg8
      - &lateralus age1643av82yp0gahkvhp46ffdzv9tlrn7we9460pdlspg2p9rm7cs5sqssjps
      - &solituboks age1hck37dgc6eapnfddnxqvyg8h25h92p5cud6svptkh2z0lmaz5c9qsmx7q3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *SussyBox
          - *waltherbox
          - *walther
          - *lateralus
          - *sveske
          - *solituboks
          - *redux
