keys:
  - users:
      - &tmp test123
  - hosts:
      - &SussyBox age103p4534fyaqcdgp0tuvydp4ex92thlry483yvgauvf5denzs7gssugurue
      - &waltherbox age1u3cls43238kr2v0gkgjfezzrcr3lqa2sfkkzw46ey6md6gnln30quhelg8
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *SussyBox
          - *waltherbox
