keys:
  - users:
      - &walther age1fx7xu2x5zymlqax9u0d6yse6kd2m98z7akxhtskhp860zrhx2qqqs65ldz
      - &sveske age1xx02tc8pj9v6hd3vctw5pnm7840alzdz8t88qaefd4e7gddl9yhsdplsp7
  - hosts:
      - &SussyBox age103p4534fyaqcdgp0tuvydp4ex92thlry483yvgauvf5denzs7gssugurue
      - &waltherbox age1u3cls43238kr2v0gkgjfezzrcr3lqa2sfkkzw46ey6md6gnln30quhelg8
      - &lateralus age1643av82yp0gahkvhp46ffdzv9tlrn7we9460pdlspg2p9rm7cs5sqssjps
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *SussyBox
          - *waltherbox
          - *walther
          - *lateralus
          - *sveske
