keys:
  - users:
      - &walther age1hqdgs3f0vz4vmzcplu87zkypltk663sdu4660h4czrx5739y4p7sv97nwg
      - &sveske age1xx02tc8pj9v6hd3vctw5pnm7840alzdz8t88qaefd4e7gddl9yhsdplsp7
      - &redux age1uq632m6453wy0ftd95wxxpay6ezvrvxk3647nyl2yvmz2wm5yehs6px3jl
  - hosts:
      - &SussyBox age103p4534fyaqcdgp0tuvydp4ex92thlry483yvgauvf5denzs7gssugurue
      - &waltherbox age1u3cls43238kr2v0gkgjfezzrcr3lqa2sfkkzw46ey6md6gnln30quhelg8
      - &lateralus age1643av82yp0gahkvhp46ffdzv9tlrn7we9460pdlspg2p9rm7cs5sqssjps
      - &solituboks age1ctvaccp8qmx79h32wprde20lkrvsuw85vqd9kmdg7qy8leq0g4cspqahy2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *SussyBox
          - *waltherbox
          - *walther
          - *lateralus
          - *sveske
          - *solituboks
          - *redux
